# Generated by Django 5.2.11 on 2026-02-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260205_1545'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            DECLARE
                idx RECORD;
            BEGIN
                FOR idx IN
                    SELECT indexname
                    FROM pg_indexes
                    WHERE tablename IN ('core_trip', 'core_driver')
                      AND indexdef LIKE '%gist%'
                LOOP
                    EXECUTE 'DROP INDEX IF EXISTS ' || idx.indexname;
                END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_location',
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(max_length=50, verbose_name='Position de destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=50, verbose_name='Position de prise en charge'),
        ),
    ]
