# Generated by Django 5.2.11 on 2026-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trip_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('van', 'Van'), ('vip', 'VIP')], default='voiture', max_length=50),
        ),
    ]
