# Generated by Django 5.2.11 on 2026-02-13 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vehicletype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position de destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position de prise en charge'),
        ),
    ]
