# Generated by Django 4.2.7 on 2026-02-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('color', models.CharField(max_length=30, verbose_name='Couleur')),
                ('plate_number', models.CharField(max_length=20, verbose_name="Plaque d'immatriculation")),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.driver')),
            ],
            options={
                'verbose_name': 'Véhicule du chauffeur',
                'verbose_name_plural': 'Véhicules des chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Permis de conduire'), ('id_card', "Carte d'identité"), ('insurance', 'Assurance'), ('vehicle_registration', 'Carte grise'), ('police_clearance', 'Casier judiciaire'), ('other', 'Autre')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_documents/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.driver')),
            ],
            options={
                'verbose_name': 'Document du chauffeur',
                'verbose_name_plural': 'Documents des chauffeurs',
            },
        ),
    ]
