# Generated by Django 4.2.7 on 2026-02-04 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('distance', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('estimated_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_shared', models.BooleanField(default=False)),
                ('sharing_discount', models.DecimalField(decimal_places=2, default=30, help_text='Pourcentage de réduction', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('special_requests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('searching', 'Recherche de chauffeur'), ('accepted', 'Accepté'), ('arrived', 'Chauffeur arrivé'), ('started', 'Commencé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.vehicletype')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_positions', models.JSONField(default=list, help_text='Historique des positions du chauffeur')),
                ('estimated_positions', models.JSONField(default=list, help_text="Positions estimées selon l'itinéraire")),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('average_speed', models.FloatField(default=0)),
                ('max_speed', models.FloatField(default=0)),
                ('distance_traveled', models.FloatField(default=0)),
                ('alerts', models.JSONField(default=list, help_text='Alertes pendant le trajet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='core.trip')),
            ],
            options={
                'verbose_name': 'Suivi de course',
                'verbose_name_plural': 'Suivis de course',
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_route', models.JSONField(help_text='Itinéraire optimisé avec waypoints')),
                ('original_distance', models.FloatField()),
                ('optimized_distance', models.FloatField()),
                ('distance_saved', models.FloatField()),
                ('fuel_saved', models.FloatField(default=0)),
                ('co2_saved', models.FloatField(default=0)),
                ('time_added', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_passengers', models.ManyToManyField(blank=True, related_name='optimized_routes', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_optimizations', to='core.trip')),
            ],
            options={
                'verbose_name': "Optimisation d'itinéraire",
                'verbose_name_plural': "Optimisations d'itinéraire",
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='booking.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='core.driver')),
            ],
            options={
                'verbose_name': 'Demande de réservation',
                'verbose_name_plural': 'Demandes de réservation',
                'ordering': ['-sent_at'],
                'unique_together': {('booking', 'driver')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='booking_boo_booking_fd5f41_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger', 'created_at'], name='booking_boo_passeng_2668fb_idx'),
        ),
    ]
